import { signOut } from "https://www.gstatic.com/firebasejs/9.15.0/firebase-auth.js"
import "./signupForm.js"
import "./signinForm.js"
import "./googleSignin.js"
import "./facebookLogin.js"
import "./githubLogin.js"
import "./logout.js"
